[programs.localnet]
next_counter = "9mTvtHmMmDTkmX6cUoXQwzp977EAzYidynANfP9NzPUG"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/gagebachik/.config/solana/id.json"

[scripts]
test = "mocha -t 1000000 tests/"
